name = "redux-reader"
compatibility_date = "2026-02-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "redux-reader-db"
database_id = "99933046-0ac3-4334-867e-2847233e4a45"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "redux-reader-articles"
