name = "redux-reader"
compatibility_date = "2026-02-14"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "redux-reader-db"
database_id = "placeholder"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "redux-reader-articles"
